### ISSUE TITLE
2nd Day - Week 2

### ISSUE THREAD

**Issue by idgm5** [harshdeepkanhai/signup-form#3]
All issues for the 2nd session of the week, please submit them in this thread. #Team94

**Comment by SevlaMare** [comment]
Is better use margin instead of <br>. Variables are not compatible with some browsers, see here: https://caniuse.com/#search=variable, when we use Sass, it will be no longer a problem.

**Comment by ghamtre** [comment]
I see that you are using a wildcard selector ( * ) to give universal variables:

```
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
```
Instead of a wildcard selector that could create conflict with the CSS hierarchy, is better if you select the main container in this case 'Body' could be a better place to add them. 

```
body {
  background-color: #eceef1;
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
```

**Comment by FrancoRosa** [comment]
The main form changes its size with the screen. Please make it with constant width
